# まえがき
JavaScriptは「非同期処理」であるので、何も待たない。それを待たせるのがPromise。

```js
new Promise((resolve, reject) => {
   // APIコール
   resolve(APIレスポンス);
}).then((result) => {
   // 処理結果を使ってReduxStoreに格納するなり
})
```
よくあるAPIコール結果を待つ場合、この`new Promise()`の部分が`axios.get()`に置き換わる。
```js
axios.get("/cards").then((apiResult) => {
   // APIコール結果を受け取る
})
```

# Promise
```js
// new Promise()するだけで、引数に渡したcallbackが実行される。
new Promise((resolve, reject) => {
    console.log("HELLO WORLD");
});
```
## 3つのステータス[pending -> resolved/rejected]
```js
// Promiseオブジェクトの最初のステータスは[pending], 非同期処理の結果次第でステータスを更新する。
new Promise((resolve, reject) => {
    console.log("What's your name?");
    const name = "DAISUKE";
    resolve(name); // 成功したらresolveする。
}).then((name) => {
    console.log(`I'm ${name}.`);
}).catch(() => {
    console.log("I'm not sure.");
})
```


## Promise.resolve(), Promise.reject()
```js
// 3. Promise.resolve() -> 戻り値: statusが[resolved]なPromiseオブジェクト
Promise.resolve("DAISUKE")
    .then((name) => console.log(`I'M ${name}`))
    .catch((errorMsg) => console.log(errorMsg));
// 4. Promise.reject()  -> 戻り値: statusが[rejected]なPromiseオブジェクト
Promise.reject("ERROR OCCURED")
    .then((name) => console.log(`I'M ${name}`))
    .catch((errorMsg) => console.log(errorMsg));
```

## Promise.all()
```js
// 引数に渡した"全てのPromiseがResolved"されたら、then()の引数に"配列(要素=各Promiseの結果)"を渡す。
Promise.all([
    new Promise((resolve, reject) => resolve(["口座情報A","口座情報B","口座情報C"])),
    new Promise((resolve, reject) => resolve(["契約A","契約B","契約C"])),
]).then((results) => {
    results.forEach((eachResult) => console.log(eachResult));
})
```

```js
// 1つでもRejectが起きた場合
// 1つでもRejectedが起きるとcatch()が実行される。
// 1番最初にRejectされたPromiseがcatch()の引数にわたる。
Promise.all([
    new Promise((resolve, reject) => resolve(["口座情報A","口座情報B","口座情報C"])),
    new Promise((resolve, reject) => resolve(["契約A","契約B","契約C"])),
    new Promise((resolve, reject) => reject("ERROR1 OCCURED")),
    new Promise((resolve, reject) => reject("ERROR2 OCCURED"))
]).then((results) => {
    results.forEach((eachResult) => console.log(eachResult));
}).catch((results) => {
    console.log(results) // ERROR1 OCCURED
})
```

## Promise()内でErrorが投げられる = catchでハンドルしないとUnhandledPromiseRejectionWarningが出るから、必ずcatchを定義すること。

✅APIを順次呼びたい場合は、promiseチェーンすればいい。

# async/awaitの登場

✅await Promise<--> とするだけで、中身の値をGETできる。
✅呼び出し元のメソッド自体を「async」に**する/できる必要**がある。

