# throwしたやつなら何でも例外となる。
throwされたやつなら、**文字列でもオブジェクトでもオブジェクトインスタンスでも**、全て例外となる。
```js
// 下記のもの全ては例外オブジェクトとして投げられる。
const error1 = "例外が発生したぞい。";
const error2 = {
    errorMsg: "例外が発生したぞい2"
}
class CustomError {
    constructor(message, status) {
        this.message = message;
        this.status = status;
    }
}
```

# よく見かける"Error()"は【ただのコンストラクタ関数】
- コンストラクタ関数 = newしてインスタンスをオブジェクトを生成するもの。
- Errorコンストラクタ関数は**messageプロパティしか持たないオブジェクト**を返す。
✅**message以外の情報を例外に持たせたいなら、自分で例外オブジェクト/クラスを定義する👍**
```js
export default class ApiError {
  constructor(
    private status: number,
    private message: string,
    private url: string
  ) {}
}

// Promise関数でエラーが起きたときに、Errorを投げる。
try {
    res = await fetch(url, { headers });
  } catch (e) {
    throw new ApiError(e.status, e.message, url);
  }
```


# catch文は1つしか書けないので、instanceOfで分岐する。
```js
try {
  throw new TypeError();
} catch (e) {
  if (e instanceof TypeError) {
    console.log('タイプエラー')
  } else {
    console.log('その他');
  }
}
```